In [ ]:
import requests
import pandas as pd
import requests
from concurrent.futures import ThreadPoolExecutor

## Create the dataset
'''
titles = pd.read_csv('titles.test.csv', index_col= 0)
titles['conceptUri'] = 'https://ec.europa.eu/esco/api/resource/occupation?uri=' + titles['conceptUri'] + '&language=en'

titles2 = titles.drop(index=list(range(13450,15463)))
titles2 = titles2.drop(index=list(range(0,13350)))

# x = requests.get('https://ec.europa.eu/esco/api/resource/occupation?uri=http://data.europa.eu/esco/occupation/47e81c7f-2d04-4a60-a8ff-9913c36d8344&language=en')

def get_url(url):
    return requests.get(url)

list_of_urls = titles2.conceptUri

with ThreadPoolExecutor(max_workers=15) as pool:
    response_list = list(pool.map(get_url,list_of_urls))

titles2['code'] = [response.json()['code'] for response in response_list]

bigdata = bigdata.append(titles2, ignore_index=True)
bigdata['codeL2'] = bigdata['code'].astype(str).str[0:4]
'''

In [3]:
titles = pd.read_csv('titles_final.csv', index_col=0)
titles

,vacancyTitle,conceptUri,code,codeL1,codeL2
0,Internship Digital Marketer,https://ec.europa.eu/esco/api/resource/occupat...,2431.10.3,243,2431
1,Marketing Executive,https://ec.europa.eu/esco/api/resource/occupat...,2431.10.3,243,2431
2,MARKETING STAFF,https://ec.europa.eu/esco/api/resource/occupat...,2431.10.3,243,2431
3,Sales representations,https://ec.europa.eu/esco/api/resource/occupat...,2431.10.3,243,2431
4,Marketing & Business Development Executive,https://ec.europa.eu/esco/api/resource/occupat...,2431.10.3,243,2431
...,...,...,...,...,...
30773,GIS Technician,https://ec.europa.eu/esco/api/resource/occupat...,2165.3,216,2165
30774,GIS Executive 2.0,https://ec.europa.eu/esco/api/resource/occupat...,2165.3,216,2165
30775,Data Digitizer,https://ec.europa.eu/esco/api/resource/occupat...,2165.3,216,2165
30776,Geomatics Surveyor (Geographic Information Sys...,https://ec.europa.eu/esco/api/resource/occupat...,2165.3,216,2165
30777,OFFSHORE SELF REGULATION,https://ec.europa.eu/esco/api/resource/occupat...,3257.4.1,325,3257

In [4]:
titles.codeL1.value_counts().head(10)

251    2975
243    2563
214    1817
522    1400
334    1292
242    1010
331     980
121     786
216     785
311     765
Name: codeL1, dtype: int64

In [5]:
train = pd.concat([titles[titles['codeL1']==251].sample(1000),
                    titles[titles['codeL1']==243].sample(1000),
                    titles[titles['codeL1']==214].sample(1000),
                    titles[titles['codeL1']==522].sample(1000),
                    titles[titles['codeL1']==334].sample(1000),
                    titles[titles['codeL1']==242].sample(1000)], ignore_index = True)
train

,vacancyTitle,conceptUri,code,codeL1,codeL2
0,Digital API Architect,https://ec.europa.eu/esco/api/resource/occupat...,2512.2,251,2512
1,SAP Basis Consultant,https://ec.europa.eu/esco/api/resource/occupat...,2511.8,251,2511
2,"EXECUTIVE, IT",https://ec.europa.eu/esco/api/resource/occupat...,2511.9,251,2511
3,Java Document Management Analyst / Developer,https://ec.europa.eu/esco/api/resource/occupat...,2511.14,251,2511
4,SAP PI/PO Integration consultant,https://ec.europa.eu/esco/api/resource/occupat...,2511.15,251,2511
...,...,...,...,...,...
5995,Supply Development Associate,https://ec.europa.eu/esco/api/resource/occupat...,2422.2,242,2422
5996,Warden & Admin,https://ec.europa.eu/esco/api/resource/occupat...,2423.3,242,2423
5997,Apprenticeship_Human Resource,https://ec.europa.eu/esco/api/resource/occupat...,2423.3,242,2423
5998,HR & Admin Officer,https://ec.europa.eu/esco/api/resource/occupat...,2423.3,242,2423
5999,HR assistant,https://ec.europa.eu/esco/api/resource/occupat...,2423.3,242,2423

In [6]:
train['label'] = 0
for row in range(len(train)):
    if train.codeL1[row] == 251:
        train.label[row] = 0
    elif train.codeL1[row] == 243:
        train.label[row] = 1
    elif train.codeL1[row] == 214:
        train.label[row] = 2
    elif train.codeL1[row] == 522:
        train.label[row] = 3
    elif train.codeL1[row] == 242:
        train.label[row] = 4
    else :
        train.label[row] = 5

train

/var/folders/y2/xqj_5hhx2l34nb6m7pndsp500000gn/T/ipykernel_1361/2394051839.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train.label[row] = 0
/var/folders/y2/xqj_5hhx2l34nb6m7pndsp500000gn/T/ipykernel_1361/2394051839.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train.label[row] = 1
/var/folders/y2/xqj_5hhx2l34nb6m7pndsp500000gn/T/ipykernel_1361/2394051839.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train.label[row] = 2
/var/folders/y2/xqj_5hhx2l34nb6m7pndsp500000gn/T/ipykernel_1361/2394051839.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train.label[row] = 3
/var/folders/y2/xqj_5hhx2l34nb6m7pndsp500000gn/T/ipykernel_1361/2394051839.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train.label[row] = 5
/var/folders/y2/xqj_5hhx2l34nb6m7pndsp500000gn/T/ipykernel_1361/2394051839.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train.label[row] = 4

,vacancyTitle,conceptUri,code,codeL1,codeL2,label
0,Digital API Architect,https://ec.europa.eu/esco/api/resource/occupat...,2512.2,251,2512,0
1,SAP Basis Consultant,https://ec.europa.eu/esco/api/resource/occupat...,2511.8,251,2511,0
2,"EXECUTIVE, IT",https://ec.europa.eu/esco/api/resource/occupat...,2511.9,251,2511,0
3,Java Document Management Analyst / Developer,https://ec.europa.eu/esco/api/resource/occupat...,2511.14,251,2511,0
4,SAP PI/PO Integration consultant,https://ec.europa.eu/esco/api/resource/occupat...,2511.15,251,2511,0
...,...,...,...,...,...,...
5995,Supply Development Associate,https://ec.europa.eu/esco/api/resource/occupat...,2422.2,242,2422,4
5996,Warden & Admin,https://ec.europa.eu/esco/api/resource/occupat...,2423.3,242,2423,4
5997,Apprenticeship_Human Resource,https://ec.europa.eu/esco/api/resource/occupat...,2423.3,242,2423,4
5998,HR & Admin Officer,https://ec.europa.eu/esco/api/resource/occupat...,2423.3,242,2423,4
5999,HR assistant,https://ec.europa.eu/esco/api/resource/occupat...,2423.3,242,2423,4

In [41]:
from sklearn.model_selection import train_test_split

X = list(train.vacancyTitle.values) # the texts --> X
y = list(train.label.values) # the labels we want to predict --> Y
labels = ['Software and applications developers and analysts', 
          'Sales, marketing and public relations professionals',
          'Engineering professionals', 
          'Shop salespersons',
          'Administrative and specialised secretaries', 
          'Administration professionals']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
X_test, X_val, y_test, y_val = train_test_split(X_test, y_test, test_size=0.5, random_state=1)

In [42]:
import tensorflow as tf
from transformers import DistilBertTokenizerFast

tokenizer = DistilBertTokenizerFast.from_pretrained('distilbert-base-cased')

train_encodings = tokenizer(X_train, truncation=True, padding=True, max_length=128) # convert input strings to BERT encodings
test_encodings = tokenizer(X_test, truncation=True, padding=True,  max_length=128)
val_encodings = tokenizer(X_val, truncation=True, padding=True, max_length=128)

train_dataset = tf.data.Dataset.from_tensor_slices((dict(train_encodings),y_train)).shuffle(1000).batch(16) # convert the encodings to Tensorflow objects
val_dataset = tf.data.Dataset.from_tensor_slices((dict(val_encodings),y_val)).batch(64)
test_dataset = tf.data.Dataset.from_tensor_slices((dict(test_encodings),y_test)).batch(64)

In [43]:
from transformers import TFDistilBertForSequenceClassification

model = TFDistilBertForSequenceClassification.from_pretrained('distilbert-base-cased', 
                                                           num_labels=len(labels))
callbacks = [
        tf.keras.callbacks.EarlyStopping(monitor='val_loss', min_delta=0, patience=8, verbose=0, 
                      mode='min', baseline=None, 
                      restore_best_weights=True)]

optimizer = tf.keras.optimizers.Adam(learning_rate=5e-5)
loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

model.compile(optimizer=optimizer, loss=loss)

Some layers from the model checkpoint at distilbert-base-cased were not used when initializing TFDistilBertForSequenceClassification: ['activation_13', 'vocab_layer_norm', 'vocab_projector', 'vocab_transform']
- This IS expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some layers of TFDistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-cased and are newly initialized: ['pre_classifier', 'classifier', 'dropout_59']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

In [54]:
model.fit(train_dataset, 
          epochs=10,
          callbacks=callbacks, 
          validation_data=val_dataset,
          batch_size=128)

Epoch 1/10
300/300 [==============================] - 639s 2s/step - loss: 0.6897 - val_loss: 0.7757
Epoch 2/10
300/300 [==============================] - 716s 2s/step - loss: 0.5138 - val_loss: 0.7496
Epoch 3/10
300/300 [==============================] - 684s 2s/step - loss: 0.3746 - val_loss: 0.7998
Epoch 4/10
300/300 [==============================] - 677s 2s/step - loss: 0.2839 - val_loss: 0.8756
Epoch 5/10
300/300 [==============================] - 642s 2s/step - loss: 0.2174 - val_loss: 0.8590
Epoch 6/10
300/300 [==============================] - 3593s 12s/step - loss: 0.1897 - val_loss: 0.9602
Epoch 7/10
300/300 [==============================] - 2965s 10s/step - loss: 0.1487 - val_loss: 1.0204
Epoch 8/10
300/300 [==============================] - 669s 2s/step - loss: 0.1280 - val_loss: 1.0986
Epoch 9/10
300/300 [==============================] - 3932s 13s/step - loss: 0.1183 - val_loss: 1.0760
Epoch 10/10
300/300 [==============================] - 635s 2s/step - loss: 0.0883 - val_loss: 1.1623

In [62]:
import numpy as np
from sklearn.metrics import classification_report 

logits = model.predict(test_dataset)
y_preds = np.argmax(logits[0], axis=1)
print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.89      0.81      0.85       103
           1       0.65      0.66      0.65        96
           2       0.85      0.77      0.80       107
           3       0.83      0.79      0.81       105
           4       0.72      0.81      0.76       102
           5       0.62      0.69      0.65        87

    accuracy                           0.76       600
   macro avg       0.76      0.75      0.75       600
weighted avg       0.76      0.76      0.76       600

In [73]:
new_examples = ["Secratry for executives", 
               "Digital promotion of products"]
examples_encodings = tokenizer(new_examples, truncation=True, padding=True)
examples_encodings = tf.data.Dataset.from_tensor_slices((
                    dict(examples_encodings)
                      )).batch(64)
pred_logits = model.predict(examples_encodings)

for i, logits in enumerate(pred_logits[0]):
    prediction = np.argmax(logits)
    print("{}: {}".format(new_examples[i], labels[prediction]))

Secratry for executives: Sales, marketing and public relations professionals
Digital promotion of products: Sales, marketing and public relations professionals

In [ ]:
model.save('model6_1000', save_format='tf')

In [2]:
from tensorflow import keras
model2 = keras.models.load_model('model6_1000')

2022-04-19 12:02:44.959093: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [ ]:
import numpy as np
from sklearn.metrics import classification_report 

logits = model2.predict(test_dataset)
y_preds = np.argmax(logits[0], axis=1)
print(classification_report(y_test, y_preds))